laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/', 'AdminHomeController@index');
    Route::get('dashboard', 'AdminHomeController@index')->name('dashboard');
    Route::get('filemanager', 'AdminHomeController@filemanager')->name('filemanager');

    Route::group(['prefix' => 'basics', 'as' => 'basics.'], function () {
        Route::group(['prefix' => 'languages', 'as' => 'languages.'], function () {
            Route::get('/', 'LanguageController@index');
            Route::get('index', 'LanguageController@index')->name('index');
            Route::get('create', 'LanguageController@create')->name('create');
            Route::get('edit/{id}', 'LanguageController@edit')->name('edit');
            Route::post('store', 'LanguageController@store')->name('store');
            Route::post('update/{id}', 'LanguageController@update')->name('update');
            Route::get('delete/{id}', 'LanguageController@delete')->name('delete');
        });

        Route::group(['prefix' => 'tables', 'as' => 'tables.'], function () {
            Route::get('/', 'TableController@index');
            Route::get('index', 'TableController@index')->name('index');
            Route::get('create', 'TableController@create')->name('create');
            Route::get('edit/{id}', 'TableController@edit')->name('edit');
            Route::post('store', 'TableController@store')->name('store');
            Route::post('update/{id}', 'TableController@update')->name('update');
            Route::get('delete/{id}', 'TableController@delete')->name('delete');
        });

        Route::group(['prefix' => 'fields', 'as' => 'fields.'], function () {
            Route::get('/', 'FieldController@index');
            Route::get('index', 'FieldController@index')->name('index');
            Route::get('create', 'FieldController@create')->name('create');
            Route::get('edit/{id}', 'FieldController@edit')->name('edit');
            Route::post('store', 'FieldController@store')->name('store');
            Route::post('update/{id}', 'FieldController@update')->name('update');
            Route::get('delete/{id}', 'FieldController@delete')->name('delete');
        });

        Route::group(['prefix' => 'tags', 'as' => 'tags.'], function () {
            Route::get('/', 'TagController@index');
            Route::get('index', 'TagController@index')->name('index');
            Route::get('create', 'TagController@create')->name('create');
            Route::get('edit/{id}', 'TagController@edit')->name('edit');
            Route::post('store', 'TagController@store')->name('store');
            Route::post('update/{id}', 'TagController@update')->name('update');
            Route::get('delete/{id}', 'TagController@delete')->name('delete');
        });

        Route::group(['prefix' => 'units', 'as' => 'units.'], function () {
            Route::get('/', 'UnitController@index');
            Route::get('index', 'UnitController@index')->name('index');
            Route::get('create', 'UnitController@create')->name('create');
            Route::get('edit/{id}', 'UnitController@edit')->name('edit');
            Route::post('store', 'UnitController@store')->name('store');
            Route::post('update/{id}', 'UnitController@update')->name('update');
            Route::get('delete/{id}', 'UnitController@delete')->name('delete');
        });
    });

    Route::group(['prefix' => 'pages', 'as' => 'pages.'], function () {
        Route::get('/', 'PageController@index');
        Route::get('index', 'PageController@index')->name('index');
        Route::get('create', 'PageController@create')->name('create');
        Route::get('edit/{id}', 'PageController@edit')->name('edit');
        Route::post('store', 'PageController@store')->name('store');
        Route::post('update/{id}', 'PageController@update')->name('update');
        Route::get('delete/{id}', 'PageController@delete')->name('delete');
    });

    Route::group(['prefix' => 'activities', 'as' => 'activities.'], function () {
        Route::get('/', 'ActivityController@index');
        Route::get('index', 'ActivityController@index')->name('index');
        Route::get('create', 'ActivityController@create')->name('create');
        Route::get('edit/{id}', 'ActivityController@edit')->name('edit');
        Route::post('store', 'ActivityController@store')->name('store');
        Route::post('update/{id}', 'ActivityController@update')->name('update');
        Route::get('delete/{id}', 'ActivityController@delete')->name('delete');
    });

    Route::group(['prefix' => 'foods', 'as' => 'foods.'], function () {
        Route::get('/', 'FoodController@index');
        Route::get('index', 'FoodController@index')->name('index');
        Route::get('create', 'FoodController@create')->name('create');
        Route::get('edit/{id}', 'FoodController@edit')->name('edit');
        Route::post('store', 'FoodController@store')->name('store');
        Route::post('update/{id}', 'FoodController@update')->name('update');
        Route::get('delete/{id}', 'FoodController@delete')->name('delete');

        Route::group(['prefix' => 'groups', 'as' => 'groups.'], function () {
            Route::get('/', 'FoodGroupController@index');
            Route::get('index', 'FoodGroupController@index')->name('index');
            Route::get('create', 'FoodGroupController@create')->name('create');
            Route::get('edit/{id}', 'FoodGroupController@edit')->name('edit');
            Route::post('store', 'FoodGroupController@store')->name('store');
            Route::post('update/{id}', 'FoodGroupController@update')->name('update');
            Route::get('delete/{id}', 'FoodGroupController@delete')->name('delete');
        });

        Route::group(['prefix' => 'sizes', 'as' => 'sizes.'], function () {
            Route::get('/', 'SizeController@index');
            Route::get('index', 'SizeController@index')->name('index');
            Route::get('create', 'SizeController@create')->name('create');
            Route::get('edit/{id}', 'SizeController@edit')->name('edit');
            Route::post('store', 'SizeController@store')->name('store');
            Route::post('update/{id}', 'SizeController@update')->name('update');
            Route::get('delete/{id}', 'SizeController@delete')->name('delete');
        });

        Route::group(['prefix' => 'facts', 'as' => 'facts.'], function () {
            Route::get('/', 'FactController@index');
            Route::get('index', 'FactController@index')->name('index');
            Route::get('create', 'FactController@create')->name('create');
            Route::get('edit/{id}', 'FactController@edit')->name('edit');
            Route::post('store', 'FactController@store')->name('store');
            Route::post('update/{id}', 'FactController@update')->name('update');
            Route::get('delete/{id}', 'FactController@delete')->name('delete');
        });
    });

    Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
        Route::get('/', 'BiosibUserController@index');
        Route::get('index', 'BiosibUserController@index')->name('index');
        Route::get('create', 'BiosibUserController@create')->name('create');
        Route::get('edit/{id}', 'BiosibUserController@edit')->name('edit');
        Route::post('store', 'BiosibUserController@store')->name('store');
        Route::post('update/{id}', 'BiosibUserController@update')->name('update');
        Route::get('delete/{id}', 'BiosibUserController@delete')->name('delete');
    });

});


Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
    Route::get('/register', 'BiosibUserController@show_register')->name('register');
    Route::post('/register', 'BiosibUserController@register')->name('register');
}); 

laravel/resources/views/partials/admin/box-information.blade.php
<div class="row">

    <!-- Feedback Box -->
    <div class="col-md-3 col-sm-6">

        <!-- BOX -->
        <div class="box danger"><!-- default, danger, warning, info, success -->

            <div class="box-title"><!-- add .noborder class if box-body is removed -->
                <h4><a href="#">{{ trans("captions.all_foods") }} ۵۴۶۳</a></h4>
                <small class="block">{{ trans("captions.count_foods") }} ۱۴۸</small>
                <i class="fa fa-coffee"></i>
            </div>

            <div class="box-body text-center">
									<span class="sparkline"
                                          data-plugin-options='{"type":"bar","barColor":"#ffffff","height":"35px","width":"100%","zeroAxis":"false","barSpacing":"2"}'>
										331,265,456,411,367,319,402,312,300,312,283,384,372,269,402,319,416,355,416,371,423,259,361,312,269,402,327
									</span>
            </div>

        </div>
        <!-- /BOX -->

    </div>

    <!-- Profit Box -->
    <div class="col-md-3 col-sm-6">

        <!-- BOX -->
        <div class="box warning"><!-- default, danger, warning, info, success -->

            <div class="box-title"><!-- add .noborder class if box-body is removed -->
                <h4>{{ trans("captions.all_messages") }} ۲۵۴۷</h4>
                <small class="block">{{ trans("captions.today_messages") }} ۱۴</small>
                <i class="fa fa-comments"></i>
            </div>

            <div class="box-body text-center">
                        <span class="sparkline"
                              data-plugin-options='{"type":"bar","barColor":"#ffffff","height":"35px","width":"100%","zeroAxis":"false","barSpacing":"2"}'>
                        331,265,456,411,367,319,402,312,300,312,283,384,372,269,402,319,416,355,416,371,423,259,361,312,269,402,327
                        </span>
            </div>

        </div>
        <!-- /BOX -->

    </div>

    <!-- Orders Box -->
    <div class="col-md-3 col-sm-6">

        <!-- BOX -->
        <div class="box default"><!-- default, danger, warning, info, success -->

            <div class="box-title"><!-- add .noborder class if box-body is removed -->
                <h4>{{ trans("captions.all_search") }} ۵۸۹۴۴</h4>
                <small class="block">{{ trans("captions.today_search") }} ۳۶</small>
                <i class="fa fa-search"></i>
            </div>

            <div class="box-body text-center">
                        <span class="sparkline"
                              data-plugin-options='{"type":"bar","barColor":"#ffffff","height":"35px","width":"100%","zeroAxis":"false","barSpacing":"2"}'>
                            331,265,456,411,367,319,402,312,300,312,283,384,372,269,402,319,416,355,416,371,423,259,361,312,269,402,327
                        </span>
            </div>

        </div>
        <!-- /BOX -->

    </div>

    <!-- Online Box -->
    <div class="col-md-3 col-sm-6">

        <!-- BOX -->
        <div class="box success"><!-- default, danger, warning, info, success -->

            <div class="box-title"><!-- add .noborder class if box-body is removed -->
                <h4>{{ trans("captions.online_users") }} ۴۶</h4>
                <small class="block">{{ trans("captions.visitors_today") }} ۳۶۸</small>
                <i class="fa fa-globe"></i>
            </div>

            <div class="box-body text-center">
									<span class="sparkline"
                                          data-plugin-options='{"type":"bar","barColor":"#ffffff","height":"35px","width":"100%","zeroAxis":"false","barSpacing":"2"}'>
										331,265,456,411,367,319,402,312,300,312,283,384,372,269,402,319,416,355,416,371,423,259,361,312,269,402,327
									</span>
            </div>

        </div>
        <!-- /BOX -->

    </div>

</div>

laravel/resources/views/partials/admin/header.blade.php
<header id="header">

    <!-- Mobile Button -->
    <button id="mobileMenuBtn"></button>

    <!-- Logo -->
    <span class="logo pull-left">
					<img src="/assets/img/logo_light.png" alt="admin panel" height="35" />
				</span>

    <form method="get" action="page-search.html" class="search pull-left hidden-xs">
        <input type="text" class="form-control" name="k" placeholder="{{ trans("captions.search") }}" />
    </form>

    <nav>

        <!-- OPTIONS LIST -->
        <ul class="nav pull-right">

            <!-- USER OPTIONS -->
            <li class="dropdown pull-left">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                    <img class="user-avatar" alt="" src="/assets/img/noavatar.png" height="34" />
                    <span class="user-name">
									<span class="hidden-xs">
										{{ trans("captions.user_admin") }} <i class="fa fa-angle-down"></i>
									</span>
								</span>
                </a>
                <ul class="dropdown-menu hold-on-click">
                    <li><!-- my inbox -->
                        <a href="#"><i class="fa fa-envelope"></i> {{ trans("captions.inbox") }}
                            <span class="pull-right label label-default">0</span>
                        </a>
                    </li>
                    <li><!-- settings -->
                        <a href="page-user-profile.html"><i class="fa fa-cogs"></i> {{ trans("captions.settings") }}</a>
                    </li>

                    <li class="divider"></li>

                    <li><!-- logout -->
                        <a href="page-login.html"><i class="fa fa-power-off"></i> {{ trans("captions.logout") }}</a>
                    </li>
                </ul>
            </li>
            <!-- /USER OPTIONS -->

        </ul>
        <!-- /OPTIONS LIST -->

    </nav>

</header>

laravel/resources/views/partials/admin/navbar.blade.php
<?php
$main_page = $sub_page = "not found";
$url = explode('/', $_SERVER['REQUEST_URI']);
if (count($url) >= 3)
    $main_page = $url[2];
if (count($url) >= 4)
    $sub_page = $url[3];
?>
<nav id="sideNav"><!-- MAIN MENU -->
    <ul class="nav nav-list">
        <li class="<?php if ($main_page == 'dashboard') echo 'active'; ?>"><!-- dashboard -->
            <a class="dashboard" href="{{ route("admin.dashboard") }}">
                <i class="main-icon fa fa-dashboard"></i> <span>{{ trans("captions.dashboard") }}</span>
            </a>
        </li>

        <li class="<?php if ($main_page == 'foods') echo 'active'; ?>"><!-- foods -->
            <a>
                <i class="fa fa-menu-arrow pull-right"></i>
                <i class="main-icon fa fa-cutlery"></i> <span>{{ trans("captions.foods") }}</span>
            </a>
            <ul><!-- submenus -->
                <li class="<?php if ($sub_page == 'groups') echo 'active'; ?>"><a
                            href="{{ route("admin.foods.groups.index") }}">{{ trans("captions.groups") }}</a></li>
                <li class="<?php if ($sub_page == 'sizes') echo 'active'; ?>"><a
                            href="{{ route("admin.foods.sizes.index") }}">{{ trans("captions.sizes") }}</a></li>
                <li class="<?php if ($sub_page == 'facts') echo 'active'; ?>"><a
                            href="{{ route("admin.foods.facts.index") }}">{{ trans("captions.facts") }}</a></li>
                <li class="<?php if ($sub_page == 'index') echo 'active'; ?>"><a
                            href="{{ route("admin.foods.index") }}">{{ trans("captions.food_info") }}</a></li>
            </ul>
        </li>

        <li class="<?php if ($main_page == 'pages') echo 'active'; ?>"><!-- pages -->
            <a href="{{ route("admin.pages.index") }}">
                <i class="main-icon fa fa-globe"></i> <span>{{ trans("captions.pages") }}</span>
            </a>
        </li>

        <li class="<?php if ($main_page == 'activities') echo 'active'; ?>"><!-- activities -->
            <a href="{{ route("admin.activities.index") }}">
                <i class="main-icon fa fa-child"></i> <span>{{ trans("captions.activities") }}</span>
            </a>
        </li>

        <li class="<?php if ($main_page == 'users') echo 'active'; ?>"><!-- users -->
            <a>
                <i class="fa fa-menu-arrow pull-right"></i>
                <i class="main-icon fa fa-users"></i> <span>{{ trans("captions.users") }}</span>
            </a>
            <ul><!-- submenus -->
                <li class="<?php if ($sub_page == 'users') echo 'active'; ?>"><a
                            href="graphs-flot.html">{{ trans("captions.add_user") }}</a></li>
                <li class="<?php if ($sub_page == 'users') echo 'active'; ?>"><a
                            href="graphs-chartjs.html">{{ trans("captions.show_users") }}</a></li>
            </ul>
        </li>

        <li class="<?php if ($main_page == 'basics') echo 'active'; ?>"><!-- basic -->
            <a>
                <i class="fa fa-menu-arrow pull-right"></i>
                <i class="main-icon fa fa-cogs"></i> <span>{{ trans("captions.basic_info") }}</span>
            </a>
            <ul><!-- submenus -->
                <li class="<?php if ($sub_page == 'languages') echo 'active'; ?>"><a
                            href="{{ route("admin.basics.languages.index") }}">{{ trans("captions.languages") }}</a>
                </li>
                <li class="<?php if ($sub_page == 'tables') echo 'active'; ?>"><a
                            href="{{ route("admin.basics.tables.index") }}">{{ trans("captions.tables") }}</a></li>
                <li class="<?php if ($sub_page == 'fields') echo 'active'; ?>"><a
                            href="{{ route("admin.basics.fields.index") }}">{{ trans("captions.fields") }}</a></li>
                <li class="<?php if ($sub_page == 'units') echo 'active'; ?>"><a
                            href="{{ route("admin.basics.units.index") }}">{{ trans("captions.units") }}</a></li>
                <li class="<?php if ($sub_page == 'tags') echo 'active'; ?>"><a
                            href="{{ route("admin.basics.tags.index") }}">{{ trans("captions.tags") }}</a></li>
            </ul>
        </li>

    </ul>

    <!-- SECOND MAIN LIST -->
    <h3>{{ trans("captions.more") }}</h3>
    <ul class="nav nav-list">
        <li class="<?php if ($main_page == 'filemanager') echo 'active'; ?>">
            <a href="{{ route("admin.filemanager") }}">
                <i class="main-icon fa fa-file"></i>
                <span>{{ trans("captions.file_manager") }}</span>
            </a>
        </li>
        <li class="<?php if ($main_page == 'index') echo 'active'; ?>">
            <a href="/">
                <i class="main-icon fa fa-link"></i>
                <span>{{ trans("captions.site_name") }}</span>
            </a>
        </li>
    </ul>

</nav>

laravel/resources/views/partials/admin/search-chart.blade.php
<div id="panel-1" class="panel panel-default">
    <div class="panel-heading">
                <span class="title elipsis">
                    <strong>{{ trans("captions.search_in_month") }}</strong> <!-- panel title -->
                    <small class="size-12 weight-300 text-mutted hidden-xs">{{ trans("captions.year_name") }}</small>
                </span>

        <!-- right options -->
        <ul class="options pull-right list-inline">
            <li><a href="#" class="opt panel_colapse" data-toggle="tooltip"
                   data-placement="bottom"></a></li>
            <li><a href="#" class="opt panel_fullscreen hidden-xs" data-toggle="tooltip"
                   data-placement="bottom"><i class="fa fa-expand"></i></a></li>
        </ul>
        <!-- /right options -->
    </div>

    <!-- panel content -->
    <div class="panel-body">

        <div id="flot-sales" class="fullwidth height-250"></div>

    </div>
    <!-- /panel content -->

    <!-- panel footer -->
    <div class="panel-footer">

        <ul class="easypiecharts list-unstyled">
            <li class="clearfix">
                <span class="stat-number">۱۸/۱۲۵</span>
                <span class="stat-title">{{ trans("captions.new_users") }}</span>
                <span class="easyPieChart" data-percent="86" data-easing="easeOutBounce" data-barColor="#F8CB00"
                      data-trackColor="#dddddd" data-scaleColor="#dddddd" data-size="60" data-lineWidth="4">
                            <span class="percent"></span>
                        </span>
            </li>

            <li class="clearfix">
                <span class="stat-number">۶۰%</span>
                <span class="stat-title">{{ trans("captions.returning_users") }}</span>

                <span class="easyPieChart" data-percent="59.83" data-easing="easeOutBounce"
                      data-barColor="#0058AA" data-trackColor="#dddddd" data-scaleColor="#dddddd" data-size="60"
                      data-lineWidth="4">
                            <span class="percent"></span>
                        </span>
            </li>

            <li class="clearfix">
                <span class="stat-number">۱۲%</span>
                <span class="stat-title">{{ trans("captions.negative_search") }}</span>

                <span class="easyPieChart" data-percent="12" data-easing="easeOutBounce" data-barColor="#F86C6B"
                      data-trackColor="#dddddd" data-scaleColor="#dddddd" data-size="60" data-lineWidth="4">
										<span class="percent"></span>
									</span>
            </li>
            <li class="clearfix">
                <span class="stat-number">۹۷%</span>
                <span class="stat-title">{{ trans("captions.positive_search") }}</span>

                <span class="easyPieChart" data-percent="97" data-easing="easeOutBounce" data-barColor="#98AD4E"
                      data-trackColor="#dddddd" data-scaleColor="#dddddd" data-size="60" data-lineWidth="4">
										<span class="percent"></span>
									</span>
            </li>
        </ul>

    </div>
    <!-- /panel footer -->
</div>