laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/', 'AdminHomeController@index');
    Route::get('dashboard', 'AdminHomeController@index')->name('dashboard');
    Route::get('filemanager', 'AdminHomeController@filemanager')->name('filemanager');

    Route::group(['prefix' => 'basics', 'as' => 'basics.'], function () {
        Route::group(['prefix' => 'languages', 'as' => 'languages.'], function () {
            Route::get('/', 'LanguageController@index');
            Route::get('index', 'LanguageController@index')->name('index');
            Route::get('create', 'LanguageController@create')->name('create');
            Route::get('edit/{id}', 'LanguageController@edit')->name('edit');
            Route::post('store', 'LanguageController@store')->name('store');
            Route::post('update/{id}', 'LanguageController@update')->name('update');
            Route::get('delete/{id}', 'LanguageController@delete')->name('delete');
        });

        Route::group(['prefix' => 'tables', 'as' => 'tables.'], function () {
            Route::get('/', 'TableController@index');
            Route::get('index', 'TableController@index')->name('index');
            Route::get('create', 'TableController@create')->name('create');
            Route::get('edit/{id}', 'TableController@edit')->name('edit');
            Route::post('store', 'TableController@store')->name('store');
            Route::post('update/{id}', 'TableController@update')->name('update');
            Route::get('delete/{id}', 'TableController@delete')->name('delete');
        });

        Route::group(['prefix' => 'fields', 'as' => 'fields.'], function () {
            Route::get('/', 'FieldController@index');
            Route::get('index', 'FieldController@index')->name('index');
            Route::get('create', 'FieldController@create')->name('create');
            Route::get('edit/{id}', 'FieldController@edit')->name('edit');
            Route::post('store', 'FieldController@store')->name('store');
            Route::post('update/{id}', 'FieldController@update')->name('update');
            Route::get('delete/{id}', 'FieldController@delete')->name('delete');
        });

        Route::group(['prefix' => 'tags', 'as' => 'tags.'], function () {
            Route::get('/', 'TagController@index');
            Route::get('index', 'TagController@index')->name('index');
            Route::get('create', 'TagController@create')->name('create');
            Route::get('edit/{id}', 'TagController@edit')->name('edit');
            Route::post('store', 'TagController@store')->name('store');
            Route::post('update/{id}', 'TagController@update')->name('update');
            Route::get('delete/{id}', 'TagController@delete')->name('delete');
        });

        Route::group(['prefix' => 'units', 'as' => 'units.'], function () {
            Route::get('/', 'UnitController@index');
            Route::get('index', 'UnitController@index')->name('index');
            Route::get('create', 'UnitController@create')->name('create');
            Route::get('edit/{id}', 'UnitController@edit')->name('edit');
            Route::post('store', 'UnitController@store')->name('store');
            Route::post('update/{id}', 'UnitController@update')->name('update');
            Route::get('delete/{id}', 'UnitController@delete')->name('delete');
        });
    });

    Route::group(['prefix' => 'pages', 'as' => 'pages.'], function () {
        Route::get('/', 'PageController@index');
        Route::get('index', 'PageController@index')->name('index');
        Route::get('create', 'PageController@create')->name('create');
        Route::get('edit/{id}', 'PageController@edit')->name('edit');
        Route::post('store', 'PageController@store')->name('store');
        Route::post('update/{id}', 'PageController@update')->name('update');
        Route::get('delete/{id}', 'PageController@delete')->name('delete');
    });

    Route::group(['prefix' => 'activities', 'as' => 'activities.'], function () {
        Route::get('/', 'ActivityController@index');
        Route::get('index', 'ActivityController@index')->name('index');
        Route::get('create', 'ActivityController@create')->name('create');
        Route::get('edit/{id}', 'ActivityController@edit')->name('edit');
        Route::post('store', 'ActivityController@store')->name('store');
        Route::post('update/{id}', 'ActivityController@update')->name('update');
        Route::get('delete/{id}', 'ActivityController@delete')->name('delete');
    });

    Route::group(['prefix' => 'foods', 'as' => 'foods.'], function () {
        Route::get('/', 'FoodController@index');
        Route::get('index', 'FoodController@index')->name('index');
        Route::get('create', 'FoodController@create')->name('create');
        Route::get('edit/{id}', 'FoodController@edit')->name('edit');
        Route::post('store', 'FoodController@store')->name('store');
        Route::post('update/{id}', 'FoodController@update')->name('update');
        Route::get('delete/{id}', 'FoodController@delete')->name('delete');

        Route::group(['prefix' => 'groups', 'as' => 'groups.'], function () {
            Route::get('/', 'FoodGroupController@index');
            Route::get('index', 'FoodGroupController@index')->name('index');
            Route::get('create', 'FoodGroupController@create')->name('create');
            Route::get('edit/{id}', 'FoodGroupController@edit')->name('edit');
            Route::post('store', 'FoodGroupController@store')->name('store');
            Route::post('update/{id}', 'FoodGroupController@update')->name('update');
            Route::get('delete/{id}', 'FoodGroupController@delete')->name('delete');
        });

        Route::group(['prefix' => 'sizes', 'as' => 'sizes.'], function () {
            Route::get('/', 'SizeController@index');
            Route::get('index', 'SizeController@index')->name('index');
            Route::get('create', 'SizeController@create')->name('create');
            Route::get('edit/{id}', 'SizeController@edit')->name('edit');
            Route::post('store', 'SizeController@store')->name('store');
            Route::post('update/{id}', 'SizeController@update')->name('update');
            Route::get('delete/{id}', 'SizeController@delete')->name('delete');
        });

        Route::group(['prefix' => 'facts', 'as' => 'facts.'], function () {
            Route::get('/', 'FactController@index');
            Route::get('index', 'FactController@index')->name('index');
            Route::get('create', 'FactController@create')->name('create');
            Route::get('edit/{id}', 'FactController@edit')->name('edit');
            Route::post('store', 'FactController@store')->name('store');
            Route::post('update/{id}', 'FactController@update')->name('update');
            Route::get('delete/{id}', 'FactController@delete')->name('delete');
        });
    });

    Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
        Route::get('/', 'BiosibUserController@index');
        Route::get('index', 'BiosibUserController@index')->name('index');
        Route::get('create', 'BiosibUserController@create')->name('create');
        Route::get('edit/{id}', 'BiosibUserController@edit')->name('edit');
        Route::post('store', 'BiosibUserController@store')->name('store');
        Route::post('update/{id}', 'BiosibUserController@update')->name('update');
        Route::get('delete/{id}', 'BiosibUserController@delete')->name('delete');
    });

});


Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
    Route::get('/register', 'BiosibUserController@show_register')->name('register');
    Route::post('/register', 'BiosibUserController@register')->name('register');
}); 

laravel/app/Models/Field.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;

class Field extends TransModel
{
    use SoftDeletes;
    protected $dates = ['deleted_at'];
}

laravel/app/Http/Controllers/FieldController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\FieldRequest;
use App\Models\Field;
use App\Models\Table;
use Illuminate\Http\Request;

class FieldController extends Controller
{
    public function index()
    {
        $fields = Field::all();
        return view("pages.fields.index")->with("fields", $fields);
    }

    public function delete(Request $request, $id)
    {
        if ($request->isMethod('get')) {
            try {
                $field = Field::find($id);
                $field->delete();
                return redirect()->route('admin.basics.fields.index');
            } catch (Exception $e) {
                return redirect()->route('admin.basics.fields.index');
            }
        }
    }

    public function create()
    {
        $table_ids = Table::all()->pluck('name', 'id');
        return view("pages.fields.create")->with('table_ids', $table_ids);
    }

    public function store(FieldRequest $request)
    {
        if ($request->ajax()) {
            $field = new Field();
            try {
                $field->name = $request->input("name");
                $field->table_id = $request->input("table_id");
                $field->save();
                return response()->json(['redirect_url' => route('admin.basics.fields.index')]);
            } catch (Exception $e) {
                return response()->json(['redirect_url' => route('admin.basics.fields.create')]);
            }
        }
    }

    public function edit($id)
    {
        $field = Field::find($id);
        $table_ids = Table::all()->pluck('name', 'id');
        return view("pages.fields.edit")->with("field", $field)->with('table_ids', $table_ids);
    }

    public function update(FieldRequest $request, $id)
    {
        if ($request->ajax()) {
            $field = Field::find($id);
            try {
                $field->name = $request->input("name");
                $field->save();
                return response()->json(['redirect_url' => route('admin.basics.fields.index')]);
            } catch (Exception $e) {
                return response()->json(['redirect_url' => route('admin.basics.fields.index')]);
            }
        }
    }
}

laravel/resources/views/pages/fields/create.blade.php
@extends("layouts.admin.form-master")

@section("main-page", trans("captions.basic_info"))

@section("sub-page", trans("captions.fields"))

@section("page-name", trans("captions.create-info"))

@section("page-icon")<i class="fa fa-cogs"></i>@endsection

@section("page-index-href", route("admin.basics.fields.index"))

@section("page-create-href", route("admin.foods.create"))

@section("form-content")
    {{ Form::open(['route' => 'admin.basics.fields.store', "id" => "entry-form"]) }}
    <fieldset>
        <div class="row">
            <div class="col-md-6 col-sm-6">
                <!-- required [php action request] -->
                <input type="hidden" name="action" value="store"/>

                <div class="row">
                    <div class="form-group">
                        <div class="col-sm-12">
                            {{ Form::label('table_id', trans("captions.table_title") . " *") }}
                            {{ Form::select("table_id", $table_ids, null, ["class" => "form-control pointer required select2"]) }}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group">
                        <div class="col-sm-12">
                            {{ Form::label('name', trans("captions.name") . " *") }}
                            <small class="text-muted">{{ trans("captions.field_title") . " ". trans("captions.regex_name") }}</small>
                            {{ Form::text("name", null, ["maxlength" => "50", "class" => "form-control", "placeholder" => trans('captions.name')]) }}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group">
                        <div class="col-sm-12">
                            <button type="submit"
                                    class="btn btn-3d btn-xlg btn-block btn-reveal btn-red">
                                <i class="fa fa-check"></i>
                                <span>{{ trans("captions.store") }}</span>
                            </button>
                        </div>
                    </div>
                </div>

            </div>
            <div class="col-md-6 col-sm-6">

            </div>
        </div>
    </fieldset>
    {{ Form::close() }}
@endsection

laravel/resources/views/pages/fields/edit.blade.php
@extends("layouts.admin.form-master")

@section("main-page", trans("captions.basic_info"))

@section("sub-page", trans("captions.tables"))

@section("page-name", trans("captions.edit-info"))

@section("page-icon")<i class="fa fa-cogs"></i>@endsection

@section("page-index-href", route("admin.basics.fields.index"))

@section("form-content")
    {{ Form::model($field, ['route' => ['admin.basics.fields.update', $field->id], "id" => "entry-form"]) }}
    <fieldset>
        <div class="row">
            <div class="col-md-6 col-sm-6">
                <!-- required [php action request] -->
                <input type="hidden" name="action" value="update"/>

                <div class="row">
                    <div class="form-group">
                        <div class="col-sm-12">
                            {{ Form::label('table_id', trans("captions.table_title") . " *") }}
                            {{ Form::select("table_id", $table_ids, null, ["class" => "form-control pointer required select2"]) }}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group">
                        <div class="col-sm-12">
                            {{ Form::label('name', trans("captions.name") . " *") }}
                            <small class="text-muted">{{ trans("captions.field_title") . " ". trans("captions.regex_name") }}</small>
                            {{ Form::text("name", null, ["maxlength" => "50", "class" => "form-control", "placeholder" => trans('captions.name')]) }}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group">
                        <div class="col-sm-12">
                            <button type="submit"
                                    class="btn btn-3d btn-xlg btn-block btn-reveal btn-red">
                                <i class="fa fa-check"></i>
                                <span>{{ trans("captions.store") }}</span>
                            </button>
                        </div>
                    </div>
                </div>

            </div>
            <div class="col-md-6 col-sm-6">

            </div>
        </div>
    </fieldset>
    {{ Form::close() }}
@endsection

laravel/resources/views/pages/fields/index.blade.php
@extends("layouts.admin.index-master")

@section("main-page", trans("captions.basic_info"))

@section("sub-page", trans("captions.fields"))

@section("page-icon")<i class="fa fa-cogs"></i>@endsection

@section("page-index-href", route("admin.basics.fields.index"))

@section("page-create-href", route("admin.basics.fields.create"))

@section("table-thead")
    <th>{{ trans("captions.name") }}</th>
    <th>{{ trans("captions.table_title") }}</th>
    <th width="45"></th>
@endsection

@section("table-tbody")
    @foreach($fields as $field)
        <tr>
            <td>{{ $field->name }}</td>
            <td>{{ $field->table->name }}</td>
            <td class="text-center">
                <a href="{{ route("admin.basics.fields.edit", $field->id) }}" class="btn btn-xs btn-warning"
                   title="{{ trans("captions.edit") }}"><i class="fa fa-pencil"></i></a>
                <a data-confirm="{{ trans("messages.info.delete") }}" onclick="delete_record('{{ route('admin.basics.fields.delete', $field->id)}}')"
                   class="btn btn-xs btn-red"
                   title="{{ trans("captions.delete") }}"><i class="fa fa-trash"></i></a>
            </td>
        </tr>
    @endforeach

@endsection